config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  # static pages controller
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'

  resources :gossips do
    resources :comments
  end
  resources :comment_likes
  resources :gossip_likes
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates_associated :users
  validates :name, presence: true
  validates :zip_code, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :commentable, polymorphic: true, optional: true, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
  
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  validates :user, presence: true
  validates :comment, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  validates :user, presence: true
  validates :gossip, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
  validates_associated :recipient_lists
  validates :content, presence: true
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  validates :title, length: { in: 3..14 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :likes, dependent: :destroy
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "please enter a valid email" }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]
  def show
  end

  def new
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def create
    @comment = Comment.new('content' => params[:content],user: User.find(current_user.id), gossip: Gossip.find(params[:gossip_id]))
    if @comment.save
        flash[:success] = "You successfuly created a comment"
        redirect_to :controller => 'gossips', :action => 'show', :id => params[:gossip_id]
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the comment creation"
      redirect_to :action => 'new'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    comment_param = params.require(:comment).permit(:content)
    if @comment.update(comment_param)
        flash[:success] = "You successfuly updated a comment"
      redirect_to :controller => 'gossips',action: 'show', :id => params[:gossip_id]
    else
      flash.now[:danger] = "Error with the comment update"
      redirect_to :action => 'edit'
    end
  end

  def destroy
    if Comment.destroy(params[:comment_id])
      flash[:success] = "You successfuly deleted a comment"
      redirect_to :controller => 'gossips', action: "show", :id => params[:id]
    else
      flash.now[:danger] = "Error with the comment deletion"
      redirect_to action: "show", :id => params[:id]
    end
  end
  
  def authenticate_user
    unless current_user 
      flash[:danger] = "This section requires to be logged-in. Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
    @nb_gossips = Gossip.where(user_id: @user.id).count
    @nb_comments = Comment.where(user_id: @user.id).count
    @gossips_arrray = Gossip.where(user_id: @user.id)
  end

  def new
    @city = City.all.order(:name)
  end

  def edit
  end

  def create
    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:email],
                    age: params[:age],
                    password: params[:password],
                    city: City.find(params[:city_id]))
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'sessions', :action => 'new'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end

  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
  def nb_comment_likes?(id)
    CommentLike.where(comment_id: id).count
  end
  def is_comment_liked?(comment_id)
    CommentLike.where(comment_id: comment_id, user: current_user).count > 0
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_likes_helper.rb
module GossipLikesHelper
  def nb_gossip_likes?(id)
    GossipLike.where(gossip_id: id).count
  end
  def is_gossip_liked?(gossip_id)
    GossipLike.where(gossip_id: gossip_id, user: current_user).count > 0
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].nil?
    return true
  end

  def is_owner?(id)
    return false if current_user.nil?
    return true if current_user.id == id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<p>Donate me money so i can implement this shit</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Donate me money so i can implement this shit</p>

app/views/comments/edit.html.erb
<!-- DISPLAY DU FORMULAIRE -->
<% content_for :title, "Edit a Comment" %>
<!-- Affichage Stylisé du Gossip-->
<% if !@comment.nil? && @comment.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your comment for the following reasons :</p>
	  <ul>
	    <% @comment.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>
<div class ='align-middle'>
	<div class="card mt-5 ml-5 mr-5" style="height:350px">
		<h5 class="card-title ml-5 pt-5 mb-2">Edit your comment</h5>
	  <div class="card-body">
		<%= form_for [@gossip,@comment] do |f| %>

	<div class=" form-group">
	<label class="card-title">Content </label>
	<%=f.text_area :content, :value => @comment.content, class: 'form-control' %>
	</div>
	<div class="form-group">
	    <button type="submit">Edit Comment </button>
	    <%= link_to 'Destroy', gossip_comment_path(comment_id: @comment.id,id: @gossip.id), class: 'btn btn-danger ml-5', method: :delete%>
	</div>
<% end %>

app/views/comments/new.html.erb
<!-- DISPLAY DU FORMULAIRE DE CREATION DE COMMENTAIRE -->
<% content_for :title, "Add a Comment" %>
<!-- Affichage Stylisé du Gossip-->
<% if !@comment.nil? && @comment.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your comment for the following reasons :</p>
	  <ul>
	    <% @comment.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>



<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:300px">
		<div class="card-body">		
			<%= form_tag gossip_comments_path do %>
			  <h5 class="cart-title"><%= label_tag 'Comment' %></h5>
			  <p class="cart-title"><%= text_area_tag 'content', @comment.content %></p>
			  <br /> <br />
			  <%= submit_tag "Add Comment", class: 'btn btn-danger' %>
			<% end %>
		</div>
	</div>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Donate me money so i can implement this shit</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Donate me money so i can implement this shit</p>