config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  # static pages controller
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'

  resources :gossips do
    resources :comments
  end
  resources :comment_likes
  resources :gossip_likes
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates_associated :users
  validates :name, presence: true
  validates :zip_code, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :commentable, polymorphic: true, optional: true, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
  
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  validates :user, presence: true
  validates :comment, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  validates :user, presence: true
  validates :gossip, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
  validates_associated :recipient_lists
  validates :content, presence: true
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  validates :title, length: { in: 3..14 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :likes, dependent: :destroy
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "please enter a valid email" }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def show
    @city = City.find(params[:id])
    @gossips_arrray = Gossip.joins(:user).where(:user => User.where(city_id: params[:id]))
    @nb_members = User.where(city_id: @city.id).count
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
    @nb_gossips = Gossip.where(user_id: @user.id).count
    @nb_comments = Comment.where(user_id: @user.id).count
    @gossips_arrray = Gossip.where(user_id: @user.id)
  end

  def new
    @city = City.all.order(:name)
  end

  def edit
  end

  def create
    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:email],
                    age: params[:age],
                    password: params[:password],
                    city: City.find(params[:city_id]))
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'sessions', :action => 'new'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end

  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
  def nb_comment_likes?(id)
    CommentLike.where(comment_id: id).count
  end
  def is_comment_liked?(comment_id)
    CommentLike.where(comment_id: comment_id, user: current_user).count > 0
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_likes_helper.rb
module GossipLikesHelper
  def nb_gossip_likes?(id)
    GossipLike.where(gossip_id: id).count
  end
  def is_gossip_liked?(gossip_id)
    GossipLike.where(gossip_id: gossip_id, user: current_user).count > 0
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].nil?
    return true
  end

  def is_owner?(id)
    return false if current_user.nil?
    return true if current_user.id == id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Donate me money so i can implement this shit</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Donate me money so i can implement this shit</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Donate me money so i can implement this shit</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Donate me money so i can implement this shit</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>

<p>Donate me money so i can implement this shit</p>

app/views/cities/show.html.erb
<% content_for :title, "City" %>

<div class ='align-middle text-center'>
	<div class="card mt-5 ml-5 mr-5" style="height:200px">
	  <div class="card-body">
	    <h5 class="card-title"> City of <%= @city.name %></h5>
	    <p class="card-title"><strong>Zip code :  	</strong><%= @city.zip_code%></p>
	    <p class="card-title"><strong>Members from this city : </strong><%= @nb_members%> </p>
	  </div>
	</div>
</div>


<!-- DISPLAY DES GOSSIPS ASSOCIES A CETTE VILLE -->
<h1 class='text-center mt-2 mb-2'>Gossips From this City</h1>
<div class='container-fluid'>
	<div class="row">
		<% @gossips_arrray.each do |gossip| %>
			<div class="col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" style="width: 18rem">
			  <div class="card-body">
			    <h5 class="card-title"><%= gossip.title %></h5>
			    <p class="card-title">A gossip from : <%= link_to gossip.user.first_name , {controller: "users", action: "show", id: gossip.user.id}%></p>
			    <div class="mb-2 text-info">
			        <span >This gossip has <%= nb_gossip_likes?(gossip.id)%> <%= nb_gossip_likes?(gossip.id) > 1 ? 'Likes' : 'Like'%></span>
			        <% if logged_in? %>
			    	    <% if is_gossip_liked?(gossip.id) %>
			    	    <span class="ml-2">
			    	    	<%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", action: "destroy", id: gossip.id}, method: :delete, style: 'color:blue'%>
			    	    </span>
			    	    <% else %>
			    	    <span class= "ml-2 text-danger">
			    	    	<%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", method: "new", id: gossip.id}, method: :post, style: 'color:red'%>
			    	    </span>
			    	    <% end %>
			    	 <%else%>
			    	    	<span class="ml-2	"><%=icon('fas', 'thumbs-up')%></span>
			    	</div>
			        <% end %>
			    </div>
			    <%= link_to "See this Gossip",{controller: "gossips", action: "show", id: gossip.id}, class: 'btn btn-primary' %>
			</div>
		<%end%>
	</div>
</div>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Donate me money so i can implement this shit</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Donate me money so i can implement this shit</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Donate me money so i can implement this shit</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Donate me money so i can implement this shit</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Donate me money so i can implement this shit</p>

app/views/users/new.html.erb
<% content_for :title, "Create an Account" %>


<% if !@user.nil? && @user.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your profile for the following reasons :</p>
	  <ul>
	    <% @user.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>



<div class="container register">
                <div class="row">
                    <div class="col-md-3 register-left">
                        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
                        <h3>Welcome</h3>
                        <p>Do you already have an Account ?</p>
                        <%= link_to 'Login to your account', new_session_path, class: 'btn btn-danger '%>
                    </div>
                    <div class="col-md-9 register-right">
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <h3 class="register-heading">Create a User Account</h3>
                                <form action= "<%= users_path %>" method="POST">
                                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

                                <div class="row register-form">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="text" name="first_name" class="form-control" placeholder="First Name *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="last_name" class="form-control" placeholder="Last Name *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" class="form-control" placeholder="Password *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="confirmpassword" class="form-control"  placeholder="Confirm Password *" value="" />
                                        </div>
                                        
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <input type="email" name="email"class="form-control" placeholder="Your Email *" value="" />
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="age"class="form-control" placeholder="Your Age *" value="" />
                                        </div>
                                        <div class="form-group row ml-2">
                                        	<%= select_tag "city_id", options_from_collection_for_select(@city, "id","name") %>
                                        	<%= link_to 'Add a city', new_city_path, class: 'btn btn-secondary btn-sm ml-2'%>
                                        </div>
                                        <div class="form-group">
                                            <input type="text" name="description"class="form-control" placeholder="Enter Your desription *" value="" />
                                        </div>
                                        <input type="submit" class="btnRegister"  value="Register"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

app/views/users/show.html.erb
<% content_for :title, "Profile" %>

<div class ='align-middle'>
	<div class="card mt-5 ml-5 mr-5" style="height:300px">
	  <div class="card-body">
	    <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
	    <p class="card-title"><strong>Age : </strong> <%= @user.age %></p>
	    <p class="card-title"><strong>From : </strong><%= link_to @city.name ,{controller: "cities", action: "show", id: @city.id}%></p>
	    <p class="card-text"> <strong>Bio:</strong><br/><%= @user.description %></p>
	    <p class="card-text"> <strong>Joined The Gossip Project : </strong><%= @user.created_at.strftime("%d/%m/%Y") %></p>
	    <p class="card-text"> <strong>Gossips shared : </strong><%= @nb_gossips %></p>
	    <p class="card-text"> <strong>Comments : </strong><%= @nb_comments %></p>
	  </div>
	</div>
</div>


<!-- DISPLAY DES GOSSIPS ASSOCIES A CET USER -->
<h1 class='text-center mt-2 mb-2'>Gossips From <%= @user.first_name %></h1>
<div class='container-fluid'>
	<div class="row">
		<% @gossips_arrray.each do |gossip| %>
			<div class="col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" style="width: 18rem">
			  <div class="card-body">
			    <h5 class="card-title"><%= gossip.title %></h5>
			    <p class="card-title">A gossip from : <%= link_to gossip.user.first_name , {controller: "users", action: "show", id: gossip.user.id}%></p>
			    <div class="mb-2">
			        <span >This gossip has <%= nb_gossip_likes?(gossip.id)%> <%= nb_gossip_likes?(gossip.id) > 1 ? 'Likes' : 'Like'%></span>
			        <% if logged_in? %>
			    	    <% if is_gossip_liked?(gossip.id) %>
			    	    <span class="ml-2">
			    	    	<%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", action: "destroy", id: gossip.id}, method: :delete, style: 'color:blue'%>
			    	    </span>
			    	    <% else %>
			    	    <span class= "ml-2 text-danger">
			    	    	<%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", method: "new", id: gossip.id}, method: :post, style: 'color:red'%>
			    	    </span>
			    	    <% end %>
			    	 <%else%>
			    	    	<span class="ml-2	"><%=icon('fas', 'thumbs-up')%></span>
			    	</div>
			        <% end %>
			    </div>
			    <%= link_to "See this Gossip", {controller: "gossips", action: "show", id: gossip.id}, class: 'btn btn-primary' %>
			  </div>
			</div>
		<%end%>
	</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Donate me money so i can implement this shit</p>