config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  # static pages controller
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'

  resources :gossips do
    resources :comments
  end
  resources :comment_likes
  resources :gossip_likes
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates_associated :users
  validates :name, presence: true
  validates :zip_code, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :commentable, polymorphic: true, optional: true, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
  
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  validates :user, presence: true
  validates :comment, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  validates :user, presence: true
  validates :gossip, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
  validates_associated :recipient_lists
  validates :content, presence: true
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  validates :title, length: { in: 3..14 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :likes, dependent: :destroy
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "please enter a valid email" }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :create, :update]


  def index
    @gossip_array = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comments = Comment.where(gossip_id: params[:id]).all
    @nb_likes = GossipLike.where(gossip_id: params[:id]).count
  end

  def new
    @tag = Tag.all
  end

  def edit    
    @gossip = Gossip.find(params[:id])
  end

  def create
    @gossip = Gossip.new(title: params[:gossip_title], content: params[:gossip_content],user: User.find(current_user.id))  # avec xxx qui sont les données obtenues à partir du formulaire
    #Gossip_tag.new(gossip_id: @gossip.id, tag: params[:select_tag])
    if @gossip.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created a gossip"
        redirect_to :action => 'show', :id => @gossip.id
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the gossip creation"
      render :action => 'new'
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(gossip_params)
      flash[:success] = "You successfuly edited a gossip"
      redirect_to action: "show", :id => @gossip.id
    else
      flash.now[:danger] = "Error with the gossip creation"
      render :action => 'edit'
    end
  end

  def destroy
    if Gossip.destroy(params[:id])
      flash[:success] = "You successfuly destroyed a gossip"
      redirect_to action: "index"
    else
      flash.now[:danger] = "Error with the gossip deletion"
      redirect_to action: "show", :id => params[:id]
    end
  end
  def authenticate_user
    unless current_user
      flash[:danger] = "This section requires to be logged-in. Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
    @nb_gossips = Gossip.where(user_id: @user.id).count
    @nb_comments = Comment.where(user_id: @user.id).count
    @gossips_arrray = Gossip.where(user_id: @user.id)
  end

  def new
    @city = City.all.order(:name)
  end

  def edit
  end

  def create
    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:email],
                    age: params[:age],
                    password: params[:password],
                    city: City.find(params[:city_id]))
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'sessions', :action => 'new'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end

  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_likes_helper.rb
module CommentLikesHelper
  def nb_comment_likes?(id)
    CommentLike.where(comment_id: id).count
  end
  def is_comment_liked?(comment_id)
    CommentLike.where(comment_id: comment_id, user: current_user).count > 0
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_likes_helper.rb
module GossipLikesHelper
  def nb_gossip_likes?(id)
    GossipLike.where(gossip_id: id).count
  end
  def is_gossip_liked?(gossip_id)
    GossipLike.where(gossip_id: gossip_id, user: current_user).count > 0
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].nil?
    return true
  end

  def is_owner?(id)
    return false if current_user.nil?
    return true if current_user.id == id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/create.html.erb
<p>Donate me money so i can implement this shit</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Donate me money so i can implement this shit</p>

app/views/gossips/edit.html.erb
<!-- DISPLAY DU FORMULAIRE -->
<% content_for :title, "Edit a Gossip" %>
<!-- Affichage Stylisé du Gossip-->
<% if !@gossip.nil? && @gossip.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your gossip for the following reasons :</p>
	  <ul>
	    <% @gossip.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>
<div class ='align-middle'>
	<div class="card mt-5 ml-5 mr-5" style="height:350px">
		<h5 class="card-title ml-5 pt-5 mb-2">Edit your Gossip</h5>
	  <div class="card-body">
		<%= form_for @gossip do |f| %>
	<div class=" form-group">
	<label class="card-title">Title </label>
	<%=f.text_field :title, class: 'form-control' %>
	<label class="card-title">Content </label>
	<%=f.text_area :content, class: 'form-control' %>
	</div>
	<div class="form-group">
	    <button type="submit">Modifier l'article </button>
	</div>
</div>

app/views/gossips/index.html.erb
<% content_for :title, "Home" %>
<!-- JUMBOTRON HERO -->

<div class="jumbotron-hero">
  <div class="container text-center" >
    <h1 class="display-4 pt-5 font-weight-bold text-dark">THE GOSSIP PROJECT</h1>
    <%= link_to "Create an account and spread your Gossips !", {controller: "gossips", action: "new"}, class: "btn btn-success btn-lg bottom"%>
  </div>
</div>


<!-- GOSSIPS DISPLAY -->
<div class="container-fluid">
  <div class="row">
    <% @gossip_array.each do |gossip| %>
    <div class= "col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" > 
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= gossip.title %></h5>
          <p class="card-title">A gossip from : <%= link_to gossip.user.first_name, {controller: "users", action: "show", id: gossip.user.id}%></p>
          <p class="card-title">This gossip has <%= Comment.where(gossip_id: gossip.id).count %> comments</p>
          <p class="mb-2 text-info">
              <span >This gossip has <%= nb_gossip_likes?(gossip.id)%> <%= nb_gossip_likes?(gossip.id) > 1 ? 'Likes' : 'Like'%></span>
              <!-- GOSSIP LIKE BUTTON-->
              <% if logged_in? %>
                <% if is_gossip_liked?(gossip.id) %>
                <span class="ml-2">
                  <%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", action: "destroy", id: gossip.id}, method: :delete, style: 'color:blue'%>
                </span>
                <% else %>
                <span class= "ml-2 text-danger">
                  <%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", method: "new", id: gossip.id}, method: :post, style: 'color:red'%>
                </span>
                <% end %>
             <%else%>
                  <span class="ml-2 "><%=icon('fas', 'thumbs-up')%></span>
              <% end %>
          </p>
          <%= link_to "See this Gossip", {controller: "gossips", action: "show", id: gossip.id}, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<!-- DISPLAY DU FORMULAIRE -->
<% content_for :title, "Add a Gossip" %>
<!-- Affichage Stylisé du Gossip-->
<% if !@gossip.nil? && @gossip.errors.any? %>
	<div class="alert alert-danger">
	  <p>We were not able to add your gossip for the following reasons :</p>
	  <ul>
	    <% @gossip.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>


<div class ='align-middle text-center'>
	<div class="card m-5 p-5" style="height:300px">
		<div class="card-body">
			<form action= "<%= gossips_path %>" method="POST">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<h3> Enter a new Gossip !</h3>
				<div class="row justify-content-center">
					<p style = "width: 200px"> Title : <input type="text" name="gossip_title"></p>
				</div>
				<div class="row justify-content-center">
				<p style = "width: 200px">Content : <input type="text" name="gossip_content"></p>
				</div>
				<!--
				<div class="row justify-content-center">
				<p style = "width: 200px">Tag : <%= select_tag "Tag", options_from_collection_for_select(@tag, "id","title") %></p>
				</div>-->
			  <p><input type="submit" value="Valider"></p>
			</form>		
		</div>
	</div>
</div>

app/views/gossips/show.html.erb
<% content_for :title, "Gossip" %>
<!-- Affichage Stylisé du Gossip-->
<div class ='align-middle text-center'>
	<div class="card mt-5 ml-5 mr-5" style="height:350px">
	  <div class="card-body">
	    <h5 class="card-title"><%= @gossip.title %></h5>
	    <p class="card-title"><%= @gossip.created_at.strftime("%d/%m/%Y") %></p>
	    <p class="card-title">A gossip shared by : <%= link_to @gossip.user.first_name, {controller: "users", action: "show", id: @gossip.user.id}%> from : <%= link_to @gossip.user.city.name , {controller: "cities", action: "show", id: @gossip.user.city.id}%></p>
	    <p class="card-text mb-5"><%= @gossip.content %></p>
	    <% if is_owner?(@gossip.user.id) %>
	    <%= link_to "Edit this Gossip", {controller: "gossips", action: "edit", id: @gossip.id}, class: 'btn btn-primary mr-5' %>
	    <%= link_to 'Destroy', gossip_path(@gossip), class: 'btn btn-danger ml-5', method: :delete%>
	    <% end %>
	    <p class="card-title text-info font-italic">
		    <span >This gossip has <%= @nb_likes%> <%= nb_gossip_likes?(@gossip.id) > 1 ? 'Likes' : 'Like'%></span>
		    <!-- BOUTON GOSSIP LIKE -->
	    <% if logged_in? %>
		    <% if is_gossip_liked?(@gossip.id) %>
		    <span class="ml-2">
		    	<%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", action: "destroy", id: @gossip.id}, method: :delete, style: 'color:blue'%>
		    </span>
		    <% else %>
		    <span class= "ml-2 text-danger">
		    	<%= link_to icon('fas', 'thumbs-up'),{controller: "gossip_likes", method: "new", id: @gossip.id}, method: :post, style: 'color:red'%>
		    </span>
		    <% end %>
		 <%else%>
		    	<span class="ml-2	"><%=icon('fas', 'thumbs-up')%></span>
		</p>
	    <% end %>

	    
	  </div>
	</div>
</div>


<!-- DISPLAY DES COMMENTAIRES -->
<h1 class='text-center mt-4 mb-4'>Comments</h1>
<h1 class='text-center mt-2 mb-2'><%= link_to "Add your comment", new_gossip_comment_path(@gossip.id), class: 'btn btn-secondary' %></h1>
<div class='container-fluid'>
	<div class="row">
		<% @comments.each do |comment| %>
			<div class="col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" style="width: 18rem">
			  <div class="card-body">
			    <h5 class="card-title">Comment from : 
					    <%= link_to comment.user.first_name , {controller: "users", action: "show", id: comment.user.id}%></h5>
				<div class="text-info font-italic">
		   			<span >This comment has <%= nb_comment_likes?(comment.id)%> <%= (nb_comment_likes?(comment.id) > 1)? 'Likes' : 'Like'%></span>

		    		    <!-- BOUTON COMMENT LIKE -->
		    	    <% if logged_in? %>
		    		    <% if is_comment_liked?(comment.id) %>
		    		    <span class="ml-2" id="liked">
		    		    	<%= link_to icon('fas', 'thumbs-up'),{controller: "comment_likes", action: "destroy", id: comment.id}, method: :delete, style: 'color:blue'%>
		    		    </span>
		    		    <% else %>
		    		    <span class= "ml-2" style="color:blue">
		    		    	<%= link_to icon('fas', 'thumbs-up'),{controller: "comment_likes", method: "new", id: comment.id}, method: :post, style: 'color:red'%>
		    		    </span>
		    		    <% end %>
		    		 <%else%>
		    		    	<span class="ml-2	"><%=icon('fas', 'thumbs-up')%></span>
		    		</div>
		    	    <% end %>
				</div>
				<p class="card-title"><%= comment.created_at.strftime("%d/%m/%Y") %></p>
			    <p class="card-title"><%= comment.content %></p>
			    <% if is_owner?(comment.user.id) %>
			    <%= link_to "Edit this comment", edit_gossip_comment_path(@gossip.id, comment.id), class: 'btn btn-secondary' %>
			    <% end %>
			  </div>
		<%end%>
	</div>
</div>

app/views/gossips/update.html.erb
<p>Donate me money so i can implement this shit</p>