config/routes.rb
Rails.application.routes.draw do
  root 'gossips#index'
  # static pages controller
  get '/static_pages/contact', to: 'static_pages#contact'
  get '/static_pages/team', to: 'static_pages#team'

  resources :gossips do
    resources :comments
  end
  resources :comment_likes
  resources :gossip_likes
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  validates_associated :users
  validates :name, presence: true
  validates :zip_code, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip, optional: true
  belongs_to :commentable, polymorphic: true, optional: true, dependent: :destroy
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  validates :content, presence: true
  
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user
  validates :user, presence: true
  validates :comment, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, length: { in: 3..14 }
  validates :content, presence: true
end

app/models/gossip_like.rb
class GossipLike < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  validates :user, presence: true
  validates :gossip, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
  validates_associated :recipient_lists
  validates :content, presence: true
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  validates :title, length: { in: 3..14 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :likes, dependent: :destroy
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "please enter a valid email" }
  validates :age, :numericality => { :greater_than_or_equal_to => 0 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @city = City.find(@user.city_id)
    @nb_gossips = Gossip.where(user_id: @user.id).count
    @nb_comments = Comment.where(user_id: @user.id).count
    @gossips_arrray = Gossip.where(user_id: @user.id)
  end

  def new
    @city = City.all.order(:name)
  end

  def edit
  end

  def create
    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:email],
                    age: params[:age],
                    password: params[:password],
                    city: City.find(params[:city_id]))
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'sessions', :action => 'new'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end

  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_likes_helper.rb
module GossipLikesHelper
  def nb_gossip_likes?(id)
    GossipLike.where(gossip_id: id).count
  end
  def is_gossip_liked?(gossip_id)
    GossipLike.where(gossip_id: gossip_id, user: current_user).count > 0
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    return false if session[:user_id].nil?
    return true
  end

  def is_owner?(id)
    return false if current_user.nil?
    return true if current_user.id == id
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--  Font Awesome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" crossorigin="anonymous">
    <!-- BOOTSWATCH -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/journal/bootstrap.min.css" rel="stylesheet" integrity="sha384-ciphE0NCAlD2/N6NUApXAN2dAs/vcSAOTzyE202jJx3oS8n4tAQezRgnlHqcJ59C" crossorigin="anonymous">

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- NAVBAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary  container-fluid">
            <%= link_to "The Gossip Project", {controller: "gossips", action: "index"}, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Add a Gossip", {controller: "gossips", action: "new"},class: "nav-link"%>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Team", {controller: "static_pages", action: "team"}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", {controller: "static_pages", action: "contact"}, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if logged_in? %>
          <li class="nav-item navbar-right">
            <%= link_to current_user.first_name, {controller: "users", action: "show", id: current_user.id}, class: "nav-link" %>
          </li>
          <li class="nav-item float-right">
            <%= link_to icon('fas', 'sign-out-alt')+"  Logout", session_path(session.id), method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="float-right">
            <%= link_to icon('fas', 'user')+"  Sign up", {controller: "users", action: "new"}, class: "nav-link" %>
          </li>
          <li class="float-right">
            <%= link_to icon('fas', 'sign-in-alt')+"  Loggin", {controller: "sessions", action: "new"}, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- FLASH MESSAGES -->

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert-#{key}" %>
    <% end %>

    <%= yield %>
  </body>
</html>